### ISSUE TITLE
استفاده در گوشی

### ISSUE THREAD

**Issue by TKZ2009** [GFW-knocker/gfw_resist_HTTPS_proxy#11]
دقیقا چطور میشه تو گوشی ازش استفاده کرد نفهمیدم منظورتون از پوشه اندروید چیه یعنی فایلو تو پوشه اندروید دانلود کنیم؟

**Comment by alizxamax** [comment]
در فایل های پروژه پوشه ای وجود داره با نام android اگر میخواید پروژه رو در اندروید اجرا کنید  از محتویات این پوشه استفاده کنید

**Comment by TKZ2009** [comment]
> در فایل های پروژه پوشه ای وجود داره با نام android اگر میخواید پروژه رو در اندروید اجرا کنید  از محتویات این پوشه استفاده کنید

خیلی ممنون چون من همون اول دانلود کردم چنین چیزی نداشت
