### ISSUE TITLE
این مشکل از کجاست؟

### ISSUE THREAD

**Issue by Saviorhoss** [GFW-knocker/gfw_resist_HTTPS_proxy#4]
online DNS Query 8.8.8.8
online DNS --> Resolved 8.8.8.8 to None
TypeError('str, bytes or bytearray expected, not NoneType')
8.8.8.8 --> 443
online DNS Query 8.8.8.8
online DNS --> Resolved 8.8.8.8 to None
TypeError('str, bytes or bytearray expected, not NoneType')

**Comment by GFW-knocker** [comment]
8.8.8.8 خودش ایپی عه. این فکر میکنه دامنه اس 
اولا ادرسو اشتباه دادین بهش
دوما dns گوگل کار نمیکنه تو ایران

**Comment by Saviorhoss** [comment]
من طبق اون چیزی که گفتین جلو رفتم چیزی رو تغییر ندادم

**Comment by GFW-knocker** [comment]
اها.
اشتباه منه. 
باید چک کنم اگه ایپی بود resolve نکنه
درستش میکنم

**Comment by GFW-knocker** [comment]
سپاس از لطف شما
کانفیگ ها اصلاح شد که رو بعضی کلاینت ها مشکل سرعت ایجاد میکرد
