### ISSUE TITLE
Discord Support

### ISSUE THREAD

**Issue by rm-NoobInCoding** [GFW-knocker/gfw_resist_HTTPS_proxy#49]
سلام
چند وقتی هست که دیسکورد توسط دادستانی فیلتر شده
با اینکه توی این زمینه هیچ تجربه ای ندارم (و احتمالا چیزی که میگم غلط باشه)
اما با استفاده از DoH یه سری دامین جدید به کد اصلی اضافه کردم که ظاهرا برای نسخه ویندوزی دیسکورد کار میده:

```
# ################# Discord working pack ###################
'updates.discord.com': '162.159.128.233',
'discord.com': '162.159.128.233',
'gateway.discord.gg': '162.159.130.234',
'status.discord.com': '162.159.136.232',
'cdn.discordapp.com': '162.159.133.233',
'images-ext-1.discordapp.net': '162.159.128.232',
'media.discordapp.net': '162.159.130.232',
'rotterdam3432.discord.media': '162.159.137.234',
'latency.discord.media': '162.159.138.234'
# ##########################################################
```

**Comment by GFW-knocker** [comment]
سلام و ممنون از زحمت شما
میشه لطفا تست کنید این کانفیگ بدون سرور که یوتیوب رو باز میکنه آیا دیسکورد رو هم باز میکنه یا خیر؟
https://github.com/GFW-knocker/gfw_resist_HTTPS_proxy/blob/main/ServerLess_TLSFrag_Xray_Config.json
در کلاینت v2rayn یا v2rayng ایمپورت میشه و احتمالا تمام سایت های پشت کلادفلر باید باز بشه

**Comment by rm-NoobInCoding** [comment]
روی ویندوز که تست کردم کار میکنه (ایرانسل)

**Comment by Aliwolf1** [comment]
سلام خسته نباشید من میخوام باهاتون ارتباط بگیرم میشه یک راه ارتباطی مثل دیسکورد یا تلگرام به بنده بدید صحبت کنیم؟

**Comment by rm-NoobInCoding** [comment]
> سلام خسته نباشید من میخوام باهاتون ارتباط بگیرم میشه یک راه ارتباطی مثل دیسکورد یا تلگرام به بنده بدید صحبت کنیم؟
Discord: rezadev
